version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://default:91238983Jonadab@painel.whatlead.com.br:6379
      - MINIO_SERVER_URL=https://minioapi.whatlead.com.br:443
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=91238983Jonadab
      - MINIO_BUCKET_NAME=curso
      - MINIO_REGION=eu-south
      - APP_SECRET=1042013feadea5404c396dc5b7eb62ed
      - DATABASE_URL=postgres://postgres:91238983Jonadab@painel.whatlead.com.br:5432/membrosflix
      - PORT=3001
      - HOST=0.0.0.0
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
